version: '3'
services:
  database:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  conjur:
    image: cyberark/conjur:latest
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]
    ports:
      - "80"

  conjur-server:
    image: nginx:alpine
    ports:
      - 443
    volumes:
      - ./test/https_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test/https_config/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ./test/https_config/dhparams.pem:/etc/nginx/dhparams.pem:ro
      - ./test/https_config/conjur.crt:/cert/tls.crt:ro
      - ./test/https_config/conjur.key:/cert/tls.key:ro
      - ./test/https_config/ca.crt:/ca/tls.crt:ro
    depends_on: [ conjur ]
